### ISSUE TITLE
Add Word Count Display and Writing Streak Tracking

### ISSUE THREAD

**Issue by ash-k121** [aswathcm29/JournalForge#68]
Please Assign this to me under 
## What feature would you like to see?
 Implement a feature that displays the word count for each journal entry and tracks the user's writing streaks (number of consecutive days writing). This feature aims to enhance user engagement by gamifying the journaling experience and motivating users to maintain a consistent writing habit.

## Why is this feature useful?
Increase user engagement with the platform

## How important is this feature to you?
- [ ] Must have

## Have you seen this feature in other projects?
- [ ] No, this is a unique idea

## Any other details?
No

## Your experience level with this project:
- [ ] I'm new here (first-time contributor)

## Would you like to work on this feature?
- [ ] Yes, I'd like to try implementing this feature

**Comment by aswathcm29** [comment]
Hey @ash-k121 That's a great idea ! I'm assigning it to you

**Comment by ash-k121** [comment]
please add gssoc ext labd level label

**Comment by aswathcm29** [comment]
That's good Im assigning it to you !

**Comment by ash-k121** [comment]
please add the level label @aswathcm29
